"""Change product price to Numeric type

Revision ID: 42efaaf36a87
Revises: bedb2d6378ed
Create Date: 2025-04-12 21:47:11.980981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42efaaf36a87'
down_revision = 'bedb2d6378ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
