"""Add index to product name and sku

Revision ID: 892425462a24
Revises: 42efaaf36a87
Create Date: 2025-04-12 23:21:57.478160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892425462a24'
down_revision = '42efaaf36a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.drop_index(batch_op.f('ix_product_name'))

    # ### end Alembic commands ###
